### ISSUE TITLE
[Bug Report] Game crash when I close the inventory.

### ISSUE THREAD

**Issue by CokeStudios** [Benjamin-Norton/RandoAssistant#21]
**Expected Behaviour**
Inventory closed.

**Actual Behaviour**
Game crashed.

**What version of the mod are you using**
1.4.0

**Helpful Files**
net.minecraft.class_148: keyPressed event handler
	at net.minecraft.class_437.method_25412(class_437.java:414) ~[client-intermediary.jar:?]
	at net.minecraft.class_309.method_1466(class_309.java:391) ~[client-intermediary.jar:?]
	at net.minecraft.class_309.method_22678(class_309.java:477) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_309.method_22676(class_309.java:477) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:288) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1241) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[Survival.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.bawnorton.randoassistant.screen.LootBookSettingsWidget.onClose()" because "this.settingsWidget" is null
	at com.bawnorton.randoassistant.screen.LootBookWidget.closeSettings(LootBookWidget.java:119) ~[randoassistant-1.4.0.jar:?]
	at net.minecraft.class_490.handler$bpf001$randoassistant$onClose(class_490.java:691) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.method_25419(class_465.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25404(class_437.java:127) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.method_25404(class_465.java:553) ~[client-intermediary.jar:?]
	at net.minecraft.class_309.method_1454(class_309.java:395) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[client-intermediary.jar:?]
	... 16 more

**Comment by Benjamin-Norton** [comment]
Ah that's mb. I'll release a patch shortly.

**Comment by Benjamin-Norton** [comment]
Fixed in 1.4.1
